# Generated by Django 3.2.5 on 2021-11-30 06:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contacts',
        ),
        migrations.RenameModel(
            old_name='portfollio',
            new_name='portfollios',
        ),
    ]
