# Generated by Django 3.2.5 on 2021-12-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_rename_description_userprofile_career_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfollios',
            name='portfolio_intro',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_intro',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='skill_intro',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
