# Generated by Django 3.2.5 on 2021-12-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20211201_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_intro', models.CharField(blank=True, max_length=30, null=True)),
                ('project_intro', models.CharField(blank=True, max_length=120, null=True)),
                ('portfolio_intro', models.CharField(blank=True, max_length=120, null=True)),
                ('service_intro', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='portfollios',
            name='portfolio_intro',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_intro',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skill_intro',
        ),
    ]
