# Generated by Django 3.2.5 on 2021-12-01 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0007_alter_intro_skill_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='connection',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
