# Generated by Django 3.2.5 on 2022-11-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
