# Generated by Django 3.2.5 on 2022-11-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_alter_projects_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='pic'),
        ),
    ]
