# Generated by Django 3.2.5 on 2022-11-27 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_auto_20221127_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='date',
            new_name='project_date',
        ),
    ]
